### PR TITLE
Create Brittany Benson (#1)

### PR DESCRIPTION
**Pull request by GreenGreaper**

### CODE REVIEW

**Comment by afeld** [comment]
1. Click `Files changed` above
1. Click the three dots to the right
1. Click `Edit file`
1. Make the following changes:

   - [ ] Change the filename from `Brittany Benson` to `GreenGreaper.json`
   - [ ] Change the content of the file to be something like:

     ```json
     {
       "emoji": "ghost",
       "introduction": "Here I am!"
     }
     ```

**Comment by afeld** [comment]
Whoops, meant to say "This is a great start! Mind making a couple of edits so your profile will show up properly?"

**Review by schmelto — CHANGES_REQUESTED** [review]
{
  "emoji": "rocket",
  "introduction": "Hope it works!"
}

**Comment by afeld** [comment]
@greengreaper I'm going to close this out since it's been open a while.

@schmelto That looks good as file content! Try opening in a new pull request.

**Pull request closed without merging**
